Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "generic/ubuntu2004"

  # VirtualBox.
  config.vm.define "vmware_desktop" do |vmware_desktop|
    vmware_desktop.vm.hostname = "lamp-drupal.test"

    config.vm.provider :vmware_desktop do |v|
      v.memory = 1024
      v.cpus = 1
    end
  end

end